user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

umowa_add_choice:
    path: /umowa/dodaj/wybierz/
    defaults:
        _controller:  FrameworkBundle:Template:template
        template:     'user/add_choice.html.twig'